name = "MAGEMin"
uuid = "e5d170eb-415a-4524-987b-12f1bce1ddab"
authors = ["Boris Kaus <kaus@uni-mainz.de> & Nicolas Riel <riel@uni-mainz.de>"]
version = "1.1.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
MAGEMin_jll = "763ebaa8-b0d2-5f6b-90ef-4fc23b5db1c4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CEnum = "0.4"
julia = "1.6"


